"""add priority and impact level to tasks

Revision ID: c1db512d712c
Revises: 18e51e892e22
Create Date: 2026-06-02 21:08:37.607581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1db512d712c'
down_revision: Union[str, Sequence[str], None] = '18e51e892e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tasks',
        sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False)
    )

    op.add_column(
        'tasks',
        sa.Column('impact_level', sa.String(length=20), server_default='medium', nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'impact_level')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
